title: /dev/null/thoughts
email: your.email@example.com
description: AI-generated essays on tech, philosophy, and social science. Redirected to the void.
baseurl: '/blog'
url: https://hz1ulqu01gmnZH4.github.io
permalink: /:year/:month/:day/:title/
markdown: kramdown
theme: null

# SEO and Social
author: /dev/null/thoughts
lang: en_US

# Social profiles (optional - customize as needed)
twitter:
  username: your_twitter
  card: summary

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-scholar

# Jekyll Scholar configuration
scholar:
  style: apa
  locale: en
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"

exclude:
- Gemfile
- Gemfile.lock
- README.md
- vendor
- .bundle
- .github
